name: carousel_slider
description: A carousel slider widget, support infinite scroll and custom child widget.
homepage: https://github.com/serenader2014/flutter_carousel_slider
repository: https://github.com/serenader2014/flutter_carousel_slider
version: 4.2.2
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
